#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -fopenmp
RESINC = 
LIBDIR = 
LIB = -lSDL -lGL -lGLU -lgomp
LDFLAGS = -s

INC_DEFAULT = $(INC)
CFLAGS_DEFAULT = $(CFLAGS)
RESINC_DEFAULT = $(RESINC)
RCFLAGS_DEFAULT = $(RCFLAGS)
LIBDIR_DEFAULT = $(LIBDIR)
LIB_DEFAULT = $(LIB)
LDFLAGS_DEFAULT = $(LDFLAGS)
OBJDIR_DEFAULT = .objs
DEP_DEFAULT = 
OUT_DEFAULT = viewer

OBJ_DEFAULT = $(OBJDIR_DEFAULT)/Part.o $(OBJDIR_DEFAULT)/freeflycamera.o $(OBJDIR_DEFAULT)/main.o $(OBJDIR_DEFAULT)/scene.o $(OBJDIR_DEFAULT)/vector3d.o

all: default

clean: clean_default

before_default: 
	test -d $(OBJDIR_DEFAULT) || mkdir -p $(OBJDIR_DEFAULT)

after_default: 

default: before_default out_default after_default

out_default: before_default $(OBJ_DEFAULT) $(DEP_DEFAULT)
	$(LD) $(LIBDIR_DEFAULT) -o $(OUT_DEFAULT) $(OBJ_DEFAULT)  $(LDFLAGS_DEFAULT) $(LIB_DEFAULT)

$(OBJDIR_DEFAULT)/Part.o: Part.cpp
	$(CXX) $(CFLAGS_DEFAULT) $(INC_DEFAULT) -c Part.cpp -o $(OBJDIR_DEFAULT)/Part.o

$(OBJDIR_DEFAULT)/freeflycamera.o: freeflycamera.cpp
	$(CXX) $(CFLAGS_DEFAULT) $(INC_DEFAULT) -c freeflycamera.cpp -o $(OBJDIR_DEFAULT)/freeflycamera.o

$(OBJDIR_DEFAULT)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEFAULT) $(INC_DEFAULT) -c main.cpp -o $(OBJDIR_DEFAULT)/main.o

$(OBJDIR_DEFAULT)/scene.o: scene.cpp
	$(CXX) $(CFLAGS_DEFAULT) $(INC_DEFAULT) -c scene.cpp -o $(OBJDIR_DEFAULT)/scene.o

$(OBJDIR_DEFAULT)/vector3d.o: vector3d.cpp
	$(CXX) $(CFLAGS_DEFAULT) $(INC_DEFAULT) -c vector3d.cpp -o $(OBJDIR_DEFAULT)/vector3d.o

clean_default: 
	rm -f $(OBJ_DEFAULT) $(OUT_DEFAULT)
	rm -rf $(OBJDIR_DEFAULT)

virtual_all: default

.PHONY: before_default after_default clean_default

